export const jsonData = [
  {
    id: 0,
    image: "assets/pixel_5.jpeg",
    otherColor: "assets/pixel5_othercolor1.jpg",
    model: "5",
    name: "Pixel 5",
    serialNo: "SKU12345-12",
    price: "$ 499",
    priceInNumber: 499,
    feature: "Smart, Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 3.5,
    color: ["Black", "White", "Blue"],
    backgroundColor: "#E3F7F4",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6.0 heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
  {
    id: 1,
    model: "6",
    image: "assets/pixel_6.jpg",
    otherColor: "assets/pixel6_othercolor1.jpg",
    name: "Pixel 6",
    serialNo: "RKM45678-45",
    price: "$ 699",
    priceInNumber: 699,
    feature: "Smart",
    rating: "1.2k",
    ratingInNo: 4,
    color: ["Black", "White", "Blue"],
    backgroundColor: "#EBF5F3",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
    processor: "Google Tensor Titan M2 security coprocessor",
  },
  {
    id: 2,
    model: "6 pro",
    image: "assets/pixel_6pro.jpg",
    otherColor: "assets/pixel6pro_othercolor1.jpg",
    name: "Pixel 6 Pro",
    serialNo: "PIX78912-78",
    price: "$ 799",
    priceInNumber: 799,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    backgroundColor: "#F7F7ED",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
];
