import { createTheme, ThemeProvider } from '@mui/material/styles';
import { makeStyles } from "@mui/styles";

export const createAccountStyle = makeStyles((theme) => ({
        container: {
          padding: '30px !important',
          width: '80% !important',
        },
        subSection1: {
          backgroundColor: '#f9fbfe !important',
          overflow: 'hidden !important',
        },
        imageIcon: {
          zIndex: 1,
          cursor: 'pointer !important',
          position: 'absolute !important',
          top: '20px !important',
          left: '50px !important ',
          width: '30px !important',
          height: '30px !important',
          objectFit: 'cover !important',
        },
        teamImage: {
          position: 'relative !important',
          top: '-40px !important',
          left: '-50px !important',
          height: '110vh !important',
          width: '90% !important',
          objectPosition: '20% -50% !important',
        },
        input:{
          display: 'block !important',
          marginTop: '10px !important',
          marginBottom: '20px !important',
          width: '100% !important',
          padding: '10px !important',
          outline: 'none !important',
          "&:hover": {
            backgroundColor: '#219ebc1a !important',
            cursor: 'pointer !important',
          },
          "&:focus": {
            border: '0.5px solid #219ebc !important',
            boxShadow: 'none !important',
            caretColor: '#219ebc !important',
            cursor: 'text !important',
          },
        },
        helperText: {
          color: '#888 !important',
          fontSize: '12px !important',
          marginTop: '5px !important',
        },
        errorMessage: {
          color: 'red !important',
          fontSize: '12px !important',
          marginTop: '5px !important',
          display: 'none !important',
        },
        inputUsernameHover: {
          backgroundColor: '#219ebc1a !important',
          cursor: 'pointer !important',
        },
        inputUsernameFocus: {
          border: '1px solid #219ebc !important',
          boxShadow: 'none !important',
          caretColor: '#219ebc !important',
          cursor: 'text !important',
        },
        inputPassword: {
          font: 'normal normal 800 14px/18px Montserrat !important',
          letterSpacing: '0px !important',
          color: '#091b29 !important',
          background: '#ffffff 0% 0% no-repeat padding-box !important',
          border: '1px solid #e4e8ee !important',
          borderRadius: '4px !important',
          marginBottom: '7px !important',
        },
        submitButton: {
          font: 'normal normal 700 14px/18px Montserrat !important',
          letterSpacing: '0px !important',
          color: '#ffffff !important',
          background: '#219ebc 0% 0% no-repeat padding-box !important',
          boxShadow: '0px 6px 10px #00000014 !important',
          borderRadius: '4px !important',
          borderColor: 'transparent !important',
          width: '101% !important',
          padding: '9px !important',
          textAlign: 'center',
          cursor: 'pointer',
          marginTop: '10px !important',
          marginBottom: '20px !important',
        },
        loginButton: {
          // display: 'block !important',
          color: 'black !important',
          backgroundColor: 'transparent !important',
          margin: 'auto auto 20px !important',
          font: 'normal normal 800 14px/18px Montserrat !important',
          boxShadow: '0px 6px 10px #00000014 !important',
          borderRadius: '4px !important',
          borderColor: 'transparent !important',
          width: '30% !important',
          padding: '9px !important',
          textAlign: 'center',
          display: 'flex',
          position: 'relative',
          left: '16px',
          justifyContent: 'center',
          cursor: 'pointer',
        },
        successCard: {
          position: 'fixed !important',
          top: '50% !important',
          left: '50% !important',
          transform: 'translate(-50%, -50%) !important',
          backgroundColor: '#ffffff !important',
          padding: '40px !important',
          borderRadius: '8px !important',
          boxShadow: '0 2px 10px rgba(0, 0, 0, 0.2) !important',
          opacity: '0 !important',
          zIndex: '-1 !important',
          transition: 'opacity 0.5s ease-in-out !important',
        },
        successText: {
          font: 'normal normal 800 18px/18px Montserrat !important',
        },
        show: {
          zIndex: '10 !important',
          opacity: '1 !important',
        },
        headingWelcome: {
          font: 'normal normal 800 24px/29px Montserrat !important',
          fontFamily: 'Montserrat, sans-serif !important',
          letterSpacing: '0.14px !important',
          color: '#091b29 !important',
        },
        headingRegister: {
          font: 'normal normal 500 18px/22px Montserrat !important',
          letterSpacing: '0.11px !important',
          color: '#bbbbbb !important',
          paddingTop: '10px !important',
          paddingBottom: '25px !important',
        },
        label: {
          font: 'normal normal 400 12px/15px Montserrat !important',
          letterSpacing: '0px !important',
          color: '#98a0ac !important',
        },
        inputUsername: {
          font: 'normal normal 600 14px/18px Montserrat !important',
          letterSpacing: '0px !important',
          color: '#091b29 !important',
          background: '#ffffff 0% 0% no-repeat padding-box !important',
          border: '1px solid #e4e8ee !important',
          borderRadius: '4px !important',
        },
        containerPassword: {
          position: 'relative !important',
          marginBottom: '0px !important',
        },
        eyeIcon: {
          position: 'relative !important',
          width: '20px !important',
          cursor: 'pointer !important',
          bottom: '35px !important',
          left: '97% !important',
          display: 'inline !important',
        },
        errorMessage:{
          color: 'red',
          position: 'relative',
          bottom: '15px',
        },
        
      
}));